/main.do=kr.co.ledger.action.UserAction
/user/registerForm.do=kr.co.ledger.action.UserAction
/user/register.do=kr.co.ledger.action.UserAction
/user/loginForm.do=kr.co.ledger.action.UserAction
/user/login.do=kr.co.ledger.action.UserAction
/user/logout.do=kr.co.ledger.action.UserAction
/user/findIdForm.do=kr.co.ledger.action.UserAction
/user/findId.do=kr.co.ledger.action.UserAction
/user/findPwForm.do=kr.co.ledger.action.UserAction
/user/findPw.do=kr.co.ledger.action.UserAction
/user/myPage.do=kr.co.ledger.action.UserAction
/user/updateForm.do=kr.co.ledger.action.UserAction
/user/updateInfo.do=kr.co.ledger.action.UserAction
/user/withdraw.do=kr.co.ledger.action.UserAction
/user/wakeup.do=kr.co.ledger.action.UserAction

/group/getInvitations.do=kr.co.ledger.action.GroupManageAction
/group/respondInvite.do=kr.co.ledger.action.GroupManageAction

/personal/getChartData.do=kr.co.ledger.action.PersonalLedgerAction
/personal/getRatioData.do=kr.co.ledger.action.PersonalLedgerAction
/personal/statistics.do=kr.co.ledger.action.PersonalLedgerAction
/personal/getTrendData.do=kr.co.ledger.action.PersonalLedgerAction