-- =====================================================================
-- 1. USERS (사용자)
-- =====================================================================
CREATE SEQUENCE SEQ_USERS NOCACHE;

CREATE TABLE USERS (
    USER_NUM NUMBER(10) PRIMARY KEY,
    USER_ID VARCHAR2(30) NOT NULL UNIQUE,
    USER_PW VARCHAR2(100) NOT NULL,
    USER_NICKNAME VARCHAR2(60) NOT NULL,
    USER_EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    USER_PHONE VARCHAR2(13) NOT NULL,
    USER_BIRTH VARCHAR2(8) NOT NULL,
    USER_STATUS CHAR(1) DEFAULT 'A' NOT NULL, 
    USER_CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    USER_LAST_LOGIN_AT DATE DEFAULT SYSDATE NOT NULL,
    BOOK_OPEN_YN CHAR(1) DEFAULT 'N' NOT NULL,
    
    CONSTRAINT CK_USER_STATUS CHECK (USER_STATUS IN ('A', 'D', 'W')),
    CONSTRAINT CK_BOOK_OPEN_YN CHECK (BOOK_OPEN_YN IN ('Y', 'N'))
);

-- =====================================================================
-- 2. PERSONAL_CATEGORIES (개인 커스텀 카테고리)
-- =====================================================================
CREATE SEQUENCE SEQ_PERSONAL_CATEGORIES NOCACHE;

CREATE TABLE PERSONAL_CATEGORIES (
    CATEGORY_NUM NUMBER(10) PRIMARY KEY,
    USER_NUM NUMBER(10) NOT NULL,
    CATEGORY_NAME VARCHAR2(60) NOT NULL,
    CATEGORY_TYPE CHAR(1) NOT NULL, 
    IS_DEFAULT_YN CHAR(1) DEFAULT 'N' NOT NULL,
    USE_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT FK_PCAT_USER FOREIGN KEY (USER_NUM) REFERENCES USERS(USER_NUM),
    CONSTRAINT CK_CATEGORY_TYPE CHECK (CATEGORY_TYPE IN ('I', 'E')),
    CONSTRAINT CK_PCAT_DEFAULT_YN CHECK (IS_DEFAULT_YN IN ('Y', 'N')),
    CONSTRAINT CK_PCAT_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

-- =====================================================================
-- 3. PERSONAL_TRANSACTIONS (개인 수입/지출 내역)
-- =====================================================================
CREATE SEQUENCE SEQ_PERSONAL_TRANSACTIONS NOCACHE;

CREATE TABLE PERSONAL_TRANSACTIONS (
    TRANS_NUM NUMBER(10) PRIMARY KEY,
    USER_NUM NUMBER(10) NOT NULL,
    CATEGORY_NUM NUMBER(10) NOT NULL,
    TRANS_TYPE CHAR(1) NOT NULL,
    TRANS_AMOUNT NUMBER(12) NOT NULL,
    TRANS_DATE DATE NOT NULL,
    TRANS_MEMO VARCHAR2(300), 
    USE_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT FK_PTRANS_USER FOREIGN KEY (USER_NUM) REFERENCES USERS(USER_NUM),
    CONSTRAINT FK_PTRANS_CAT FOREIGN KEY (CATEGORY_NUM) REFERENCES PERSONAL_CATEGORIES(CATEGORY_NUM),
    CONSTRAINT CK_TRANS_TYPE CHECK (TRANS_TYPE IN ('I', 'E')),
    CONSTRAINT CK_TRANS_AMOUNT CHECK (TRANS_AMOUNT > 0),
    CONSTRAINT CK_PTRANS_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

-- =====================================================================
-- 4. GROUPS (공동 가계부 방 정보)
-- =====================================================================
CREATE SEQUENCE SEQ_GROUPS NOCACHE;

CREATE TABLE GROUPS (
    GROUP_NUM NUMBER(10) PRIMARY KEY,
    GROUP_NAME VARCHAR2(60) NOT NULL,
    GROUP_DESC VARCHAR2(300), 
    GROUP_TYPE CHAR(1) NOT NULL, 
    GROUP_OWNER_NUM NUMBER(10) NOT NULL,
    GROUP_OPEN_YN CHAR(1) DEFAULT 'N' NOT NULL,
    SETTLE_USE_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    USE_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT FK_GROUPS_OWNER FOREIGN KEY (GROUP_OWNER_NUM) REFERENCES USERS(USER_NUM),
    CONSTRAINT CK_GROUP_TYPE CHECK (GROUP_TYPE IN ('I', 'M')),
    CONSTRAINT CK_GROUP_OPEN_YN CHECK (GROUP_OPEN_YN IN ('Y', 'N')),
    CONSTRAINT CK_SETTLE_USE_YN CHECK (SETTLE_USE_YN IN ('Y', 'N')),
    CONSTRAINT CK_GROUP_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

-- =====================================================================
-- 5. GROUP_MEMBERS (방-유저 연결)
-- =====================================================================
CREATE SEQUENCE SEQ_GROUP_MEMBERS NOCACHE;

CREATE TABLE GROUP_MEMBERS (
    MEMBER_NUM NUMBER(10) PRIMARY KEY,
    GROUP_NUM NUMBER(10) NOT NULL,
    USER_NUM NUMBER(10) NOT NULL,
    JOIN_DATE DATE DEFAULT SYSDATE NOT NULL,
    MEMBER_STATUS CHAR(1) DEFAULT 'A' NOT NULL, 
    
    CONSTRAINT FK_GMEM_GROUP FOREIGN KEY (GROUP_NUM) REFERENCES GROUPS(GROUP_NUM),
    CONSTRAINT FK_GMEM_USER FOREIGN KEY (USER_NUM) REFERENCES USERS(USER_NUM),
    CONSTRAINT CK_MEMBER_STATUS CHECK (MEMBER_STATUS IN ('A', 'W'))
);

-- =====================================================================
-- 6. INVITATIONS (초대장 관리)
-- =====================================================================
CREATE SEQUENCE SEQ_INVITATIONS NOCACHE;

CREATE TABLE INVITATIONS (
    INVITE_NUM NUMBER(10) PRIMARY KEY,
    GROUP_NUM NUMBER(10) NOT NULL,
    INVITER_NUM NUMBER(10) NOT NULL,
    INVITEE_NUM NUMBER(10) NOT NULL,
    INVITE_STATUS CHAR(1) DEFAULT 'P' NOT NULL, 
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT FK_INV_GROUP FOREIGN KEY (GROUP_NUM) REFERENCES GROUPS(GROUP_NUM),
    CONSTRAINT FK_INV_SENDER FOREIGN KEY (INVITER_NUM) REFERENCES USERS(USER_NUM),
    CONSTRAINT FK_INV_RECEIVER FOREIGN KEY (INVITEE_NUM) REFERENCES USERS(USER_NUM),
    CONSTRAINT CK_INVITE_STATUS CHECK (INVITE_STATUS IN ('P', 'A', 'R'))
);

-- =====================================================================
-- 7. LEDGER_PERIODS (장부 주기 구분)
-- =====================================================================
CREATE SEQUENCE SEQ_LEDGER_PERIODS NOCACHE;

CREATE TABLE LEDGER_PERIODS (
    PERIOD_NUM NUMBER(10) PRIMARY KEY,
    GROUP_NUM NUMBER(10) NOT NULL,
    PERIOD_SEQ NUMBER(5) NOT NULL,
    PERIOD_START_DATE DATE DEFAULT SYSDATE NOT NULL,
    PERIOD_END_DATE DATE, 
    PERIOD_STATUS CHAR(1) DEFAULT 'O' NOT NULL, 
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT FK_PERIOD_GROUP FOREIGN KEY (GROUP_NUM) REFERENCES GROUPS(GROUP_NUM),
    CONSTRAINT CK_PERIOD_STATUS CHECK (PERIOD_STATUS IN ('O', 'C'))
);

-- =====================================================================
-- 8. GROUP_CATEGORIES (그룹 커스텀 카테고리)
-- =====================================================================
CREATE SEQUENCE SEQ_GROUP_CATEGORIES NOCACHE;

CREATE TABLE GROUP_CATEGORIES (
    GCATEGORY_NUM NUMBER(10) PRIMARY KEY,
    GROUP_NUM NUMBER(10) NOT NULL,
    CATEGORY_NAME VARCHAR2(60) NOT NULL,
    IS_DEFAULT_YN CHAR(1) DEFAULT 'N' NOT NULL,
    USE_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT FK_GCAT_GROUP FOREIGN KEY (GROUP_NUM) REFERENCES GROUPS(GROUP_NUM),
    CONSTRAINT CK_GCAT_DEFAULT_YN CHECK (IS_DEFAULT_YN IN ('Y', 'N')),
    CONSTRAINT CK_GCAT_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

-- =====================================================================
-- 9. GROUP_TRANSACTIONS (공동 지출 내역)
-- =====================================================================
CREATE SEQUENCE SEQ_GROUP_TRANSACTIONS NOCACHE;

CREATE TABLE GROUP_TRANSACTIONS (
    GTRANS_NUM NUMBER(10) PRIMARY KEY,
    GROUP_NUM NUMBER(10) NOT NULL,
    PERIOD_NUM NUMBER(10) NOT NULL,
    GCATEGORY_NUM NUMBER(10) NOT NULL,
    USER_NUM NUMBER(10) NOT NULL,
    TRANS_AMOUNT NUMBER(12) NOT NULL,
    TRANS_DATE DATE NOT NULL,
    TRANS_MEMO VARCHAR2(300), 
    USE_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT FK_GTRANS_GROUP FOREIGN KEY (GROUP_NUM) REFERENCES GROUPS(GROUP_NUM),
    CONSTRAINT FK_GTRANS_PERIOD FOREIGN KEY (PERIOD_NUM) REFERENCES LEDGER_PERIODS(PERIOD_NUM),
    CONSTRAINT FK_GTRANS_CAT FOREIGN KEY (GCATEGORY_NUM) REFERENCES GROUP_CATEGORIES(GCATEGORY_NUM),
    CONSTRAINT FK_GTRANS_USER FOREIGN KEY (USER_NUM) REFERENCES USERS(USER_NUM),
    CONSTRAINT CK_GTRANS_AMOUNT CHECK (TRANS_AMOUNT > 0),
    CONSTRAINT CK_GTRANS_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

-- =====================================================================
-- 10. EXPENSE_LOGS (지출 수정/삭제 히스토리 로그)
-- =====================================================================
CREATE SEQUENCE SEQ_EXPENSE_LOGS NOCACHE;

CREATE TABLE EXPENSE_LOGS (
    LOG_NUM NUMBER(10) PRIMARY KEY,
    GTRANS_NUM NUMBER(10) NOT NULL,
    ACTION_USER_NUM NUMBER(10) NOT NULL,
    ACTION_TYPE CHAR(1) NOT NULL, 
    BEFORE_AMOUNT NUMBER(12) NOT NULL,
    AFTER_AMOUNT NUMBER(12), 
    BEFORE_CATEGORY VARCHAR2(60) NOT NULL,
    AFTER_CATEGORY VARCHAR2(60), 
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT FK_LOG_GTRANS FOREIGN KEY (GTRANS_NUM) REFERENCES GROUP_TRANSACTIONS(GTRANS_NUM),
    CONSTRAINT FK_LOG_ACTION_USER FOREIGN KEY (ACTION_USER_NUM) REFERENCES USERS(USER_NUM),
    CONSTRAINT CK_ACTION_TYPE CHECK (ACTION_TYPE IN ('U', 'D'))
);

-- =====================================================================
-- 11. SETTLEMENT_SNAPSHOTS (정산결과 스냅샷)
-- =====================================================================
CREATE SEQUENCE SEQ_SETTLEMENT_SNAPSHOTS NOCACHE;

CREATE TABLE SETTLEMENT_SNAPSHOTS (
    SETTLE_NUM NUMBER(10) PRIMARY KEY,
    PERIOD_NUM NUMBER(10) NOT NULL,
    PAYER_USER_NUM NUMBER(10) NOT NULL,
    RECEIVER_USER_NUM NUMBER(10) NOT NULL,
    SETTLE_AMOUNT NUMBER(12) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT FK_SNAP_PERIOD FOREIGN KEY (PERIOD_NUM) REFERENCES LEDGER_PERIODS(PERIOD_NUM),
    CONSTRAINT FK_SNAP_PAYER FOREIGN KEY (PAYER_USER_NUM) REFERENCES USERS(USER_NUM),
    CONSTRAINT FK_SNAP_RECEIVER FOREIGN KEY (RECEIVER_USER_NUM) REFERENCES USERS(USER_NUM),
    CONSTRAINT CK_SETTLE_AMOUNT CHECK (SETTLE_AMOUNT > 0)
);